// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://seuaqqikpwzrwatfkkxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNldWFxcWlrcHd6cndhdGZra3hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3MzU2NTIsImV4cCI6MjA1NTMxMTY1Mn0.c221duO4KPWgmWT6ALDv3xgb8j1alU0RIB4y_p8pr64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);